version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data


  webserver:
    build:
      context: .      # Build custom Airflow image
    depends_on:
      - postgres
    env_file: .env               # Loads Spotify + AWS creds into Airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "myFernetKey"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mediaanalyzer123"
      AIRFLOW_CONN_SNOWFLAKE_CONN: snowflake://username:password@/SCHEMA?account=myaccount&database=MYDB&region=us-west-2&warehouse=MyWarehouse
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins

      # REQUIRED — so your DAG can import ingest.py and clean_spotify.py
      - ./ingestion:/opt/airflow/ingestion
      - ./transform:/opt/airflow/transform
      - ./spotify_cache:/opt/airflow/spotify_cache


    ports:
      - "8080:8080"
    command: airflow webserver


  scheduler:
    build:
      context: .        # same custom Airflow image
    depends_on:
      - webserver
      - postgres
    env_file: .env               # Load .env for PythonOperator
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "myFernetKey"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mediaanalyzer123"
      AIRFLOW_CONN_SNOWFLAKE_CONN: snowflake://username:password@/SCHEMA?account=myaccount&database=MYDB&region=us-west-2&warehouse=MyWarehouse
      
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins

      # REQUIRED — scheduler executes PythonOperators
      - ./ingestion:/opt/airflow/ingestion
      - ./transform:/opt/airflow/transform
      - ./spotify_cache:/opt/airflow/spotify_cache
    command: airflow scheduler


volumes:
  airflow_db:
